--- #YAML:1.0
name:               CGI-FormBuilder-Config-Simple
version:            0.09
abstract:           deploy web forms w/ .ini file  
author:
    - Hugh Esco <hesco@campaignfoundations.com>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    CGI::FormBuilder:     0
    Config::Simple:       0
    Cwd:                  0
    Data::Dumper:         0
    DBI:                  0
    ExtUtils::MakeMaker:  0
    Test::DatabaseRow:    0
    Test::More:           0
    WWW::Mechanize:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
